### Get all pets
GET http://localhost:3000/pets
Accept: application/json

### Get libro by ID
GET http://localhost:3000/pets/69735b1c697a34075675d002
Accept: application/json

### Delete libro by ID
DELETE http://localhost:3000/pets/6967edfb8768ad4a16f7a7aa
Accept: application/json

### Create a new libro
POST http://localhost:3000/pets
Content-Type: application/json

{
  "nombre": "jeje",
  "raza": "alguna",
  "foto": "una buena",
  "descripcion": "si"
}

### Update a libro by ID
PUT http://localhost:3000/pets/6967ef71eaa217cc9a3aef5f
Content-Type: application/json

{
  "descripcion": "no"
}

### Create user
POST http://localhost:3000/users
Content-Type: application/json

{
  "nombre": "usuario",
  "clave": "1234"
}

### Get all users
GET http://localhost:3000/users
Accept: application/json

### Get a user
GET http://localhost:3000/users/usuario
Accept: application/json