### Get all pets
GET http://localhost:3000/api/albums
Accept: application/json

### Get producto by ID
GET http://localhost:3000/api/albums/697c82ce3e6faeccbafbe45d
Accept: application/json

### Delete producto by ID
DELETE http://localhost:3000/api/albums/697c83823e6faeccbafbe45e
Accept: application/json

### Create a product
POST http://localhost:3000/api/albums/new
Content-Type: application/json

{
  "title": "titulo4",
  "artist": "2015",
  "year": 2014,
  "genre": "accion",
  "coverUrl": "foto.png"
  }


### Update a producto by ID
PUT http://localhost:3000/api/albums/697a57dd66ecbe0c20dd9062
Content-Type: application/json

{
  "title": "titulo1",
  "year": "2015",
  "genre": "accion",
  "rating": 5,
  "platform": "Netflix",
  "imageUrl": "http://example.com/image.jpg"
}
