### Get all pets
GET http://localhost:3000/users
Accept: application/json

### Get libro by ID
GET http://localhost:3000/pets/69735b1c697a34075675d002
Accept: application/json

### Delete libro by ID
DELETE http://localhost:3000/users/6973d747bc5c12ef79b34be6
Accept: application/json

### login a user admin
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "name": "jorgeAdmin",
  "password": "admin"
}

### Create a user admin
POST http://localhost:3000/users/register
Content-Type: application/json

{
  "name": "jorgeAdmin",
  "password": "admin",
  "admin": true
}

### Create a user no admin
POST http://localhost:3000/users/register
Content-Type: application/json

{
  "name": "jorge",
  "password": "noadmin",
  "admin": false
}

### Update a libro by ID
PUT http://localhost:3000/pets/6970f9edf37902353204fc2f
Content-Type: application/json

{
  "nombre": "jeje",
  "raza": "alguna",
  "foto": "una buena",
  "estado": "sold",
  "descripcion": "si"
}

### Create user
POST http://localhost:3000/users
Content-Type: application/json

{
  "nombre": "usuario",
  "clave": "1234"
}

### Get all users
GET http://localhost:3000/users
Accept: application/json

### Get a user
GET http://localhost:3000/users/usuario
Accept: application/json

### Delete libro by ID
DELETE http://localhost:3000/users/6973981733a95d1d5f3361e7
Accept: application/json

### Create a user no admin
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "jorge",
  "description": "producto",
  "price": 15
}

### Get all pets
GET http://localhost:3000/products
Accept: application/json